version: '3.8'

services:
  app:
    build: .
    container_name: book-review-api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules 
    command: npm run dev

  postgres:
    image: postgres:13
    container_name: book-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookreview
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: book-cache
    ports:
      - '6379:6379'

volumes:
  pgdata:
